server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movies/**

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**
